FROM quay.io/openshift/origin-jenkins:latest

# labels
ENV DESCRIPTION="Ploigos version of Jenkins allowing for runtime changes of ca-trust."
LABEL \
    maintainer="Ploigos <ploigos@redhat.com>" \
    name="ploigos/ploigos-jenkins" \
    summary="$DESCRIPTION" \
    description="$DESCRIPTION" \
    License="GPLv2+" \
    architecture="x86_64" \
    io.k8s.display-name="Ploigos - CI Agent - Jenkins" \
    io.k8s.description="$DESCRIPTION" \
    io.openshift.expose-services="" \
    io.openshift.tags="ploigos,jenkins" \
    com.redhat.component="ploigos-jenkins-container"

USER root

# Allow root(0) group to run update-ca-trust extract
RUN chmod -R g+w /etc/pki/ca-trust/extracted
