ARG FROM_IMAGE=quay.io/ploigos/ploigos-base-java-8:latest

FROM $FROM_IMAGE
ARG PLOIGOS_USER_UID

# Labels consumed by Red Hat build service
LABEL com.redhat.component="ploigos-ci-agent-jenkins" \
      name="ploigos/ploigos-ci-agent-jenkins" \
      architecture="x86_64" \
      io.k8s.display-name="Jenkins Agent" \
      io.k8s.description="The Ploigos jenkins agent" \
      io.openshift.tags="ploigos,openshift,java,jenkins,agent,python,python3,python36" \
      maintainer="ploigos@redhat.com"

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

USER root

# Copy the entrypoint
ADD contrib/bin/* /usr/local/bin/

# Install jenkins agent
RUN chmod 775 /usr/bin && \
    chmod 775 /usr/share/man/man1 && \
    chmod 775 /usr/lib/jvm && \
    unlink /usr/lib/jvm/jre && \
    unlink /usr/lib/jvm/java && \
    mkdir -p /var/lib/origin && \
    chmod 775 /var/lib/origin &&\
    chmod 550 /usr/local/bin/run-jnlp-client && \
    chown 1001:0 /usr/local/bin/run-jnlp-client

USER $PLOIGOS_USER_UID

# Run the Jenkins JNLP client
ENTRYPOINT ["/usr/local/bin/run-jnlp-client"]

##############################################
# End
##############################################
