ARG BASE_IMAGE=quay.io/ploigos/ploigos-tool-javascript:latest.ubi8

FROM $BASE_IMAGE
ARG PLOIGOS_USER_UID
ARG SONAR_CLI=sonar-scanner-cli-6.1.0.4477-linux-x64
ARG SONAR=sonar-scanner-6.1.0.4477-linux-x64

# labels
ENV DESCRIPTION="Ploigos tool container with Sonar CLI."
LABEL \
    maintainer="Ploigos <ploigos@redhat.com>" \
    name="ploigos/ploigos-tool-sonar" \
    summary="$DESCRIPTION" \
    description="$DESCRIPTION" \
    License="GPLv2+" \
    architecture="x86_64" \
    io.k8s.display-name="Ploigos - Tool - sonar" \
    io.k8s.description="$DESCRIPTION" \
    io.openshift.expose-services="" \
    io.openshift.tags="ploigos,sonar" \
    com.redhat.component="ploigos-tool-sonar-container"

USER root

# Goal:
#    Install sonar-scanner for CLI.
#    Put $SONAR/bin in the PATH per documentation:
#        https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
# Hint:
#    The executable is named sonar-scanner.
#    In python to execute, substitute the dash with underscore, eg: sh.sonar_scanner()
#        https://amoffat.github.io/sh/sections/faq.html
WORKDIR /usr/bin
RUN curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/${SONAR_CLI}.zip -o sonar.zip && \
    unzip ./sonar.zip && \
    rm ./sonar.zip && \
    mv ./${SONAR} ./sonar && \
    chown -R 1001:0 /usr/bin/sonar

ENV PATH /usr/bin/sonar/bin:$PATH

# may not actually be able to run as this user at runtime
# but platforms like OpenShift will still respect users home directory
# so still worth setting
USER ${PLOIGOS_USER_UID}
