ARG FROM_IMAGE=quay.io/ploigos/ploigos-base:latest

FROM $FROM_IMAGE
ARG PLOIGOS_USER_UID

# Labels consumed by Red Hat build service
LABEL com.redhat.component="ploigos-tool-rekor" \
      name="ploigos/ploigos-tool-rekor" \
      architecture="x86_64" \
      io.k8s.display-name="Rekor-cli Tool" \
      io.k8s.description="The Ploigos Rekor-cli tool" \
      io.openshift.tags="ploigos,jenkins,rekor" \
      maintainer="ploigos@redhat.com"

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

USER root

# Copy the entrypoint
ADD contrib/centos.repo /etc/yum.repos.d/

# Install jenkins agent
RUN git clone https://github.com/sigstore/rekor.git && \
    yum install golang maven -y && \
    cd rekor && \
    go build ./cmd/rekor-cli && \
    mv rekor-cli /usr/local/bin/rekor && \
    chmod 775 /usr/bin && \
    chmod 777 /usr/local/bin/rekor && \
    chown 1001:0 /usr/local/bin/rekor

USER $PLOIGOS_USER_UID


##############################################
# End
##############################################
