##############################################
# Stage 1 : Build go-init
##############################################
FROM openshift/origin-release:golang-1.12 AS go-init-builder
WORKDIR  /go/src/github.com/openshift/jenkins
COPY . .
WORKDIR  /go/src/github.com/openshift/jenkins/go-init
RUN go build . && cp go-init /usr/bin

##############################################
# Stage 3 : Build Maven Jenkins Agent with 
#           go-init
##############################################
FROM quay.io/tssc/tssc-maven:latest
MAINTAINER tbd <nobody@nowhere.com>
COPY --from=go-init-builder /usr/bin/go-init /usr/bin/go-init

# Labels consumed by Red Hat build service
LABEL com.redhat.component="tssc-ubi8-maven-jenkins-agent" \
      name="openshift4/tssc-ubi8-maven-jenkins-agent" \
      architecture="x86_64" \
      io.k8s.display-name="Maven Jenkins Agent" \
      io.k8s.description="The TSSC jenkins agent maven image" \
      io.openshift.tags="openshift,java,maven,jenkins,agent,python,python3,python36" \
      maintainer="nobody@nowhere.com"      

ENV HOME=/home/jenkins \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    MAVEN_OPTS="-Duser.home=$HOME"

USER root
# Install jenkins agent
RUN dnf update -y && \
    dnf clean all && \
    mkdir -p /home/jenkins && \
    chown -R 1001:0 /home/jenkins && \
    chmod -R g+w /home/jenkins 

# Copy the entrypoint
ADD contrib/bin/* /usr/local/bin/

# Run the Jenkins JNLP client
ENTRYPOINT ["/usr/bin/go-init", "-main", "/usr/local/bin/run-jnlp-client"]

##############################################
# End
##############################################
