#FROM quay.io/tssc/tssc-maven:latest
FROM tssc-maven:latest
MAINTAINER Red Hat TSSC <napsspo+tssc@redhat.com>

# Labels consumed by Red Hat build service
LABEL com.redhat.component="tssc-ubi8-maven-jenkins-agent" \
      name="openshift4/tssc-ubi8-maven-jenkins-agent" \
      architecture="x86_64" \
      io.k8s.display-name="Maven Jenkins Agent" \
      io.k8s.description="The TSSC jenkins agent maven image" \
      io.openshift.tags="openshift,java,maven,jenkins,agent,python,python3,python36" \
      maintainer="napsspo+tssc@redhat.com" 

ENV HOME=/home/jenkins \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    MAVEN_OPTS="-Duser.home=$HOME"

USER root

# Copy the entrypoint
ADD contrib/bin/* /usr/local/bin/

# Install jenkins agent
RUN dnf update -y && \
    dnf clean all && \
    # Following 9 lines are requred for run-jnlp-client
    chmod -R 775 /etc/alternatives && \
    chmod -R 775 /var/lib/alternatives && \
    chmod 775 /usr/bin && \
    chmod 775 /usr/share/man/man1 && \
    chmod 775 /usr/lib/jvm && \
    unlink /usr/lib/jvm/jre && \
    unlink /usr/lib/jvm/java && \
    mkdir -p /var/lib/origin && \
    chmod 775 /var/lib/origin &&\
    mkdir -p /home/jenkins && \
    chown -R 1001:0 /home/jenkins && \
    chmod 550 /usr/local/bin/run-jnlp-client && \
    chown 1001:0 /usr/local/bin/run-jnlp-client && \
    chmod -R g+w /home/jenkins 


USER 1001

# Run the Jenkins JNLP client
ENTRYPOINT ["/usr/local/bin/run-jnlp-client"]

##############################################
# End
##############################################
