name: tssc-maven-jenkins-agent-pr
on:
  pull_request:
    paths:
      - tssc-maven-jenkins-agent/**
jobs:
  build:
    env:
      context: tssc-maven-jenkins-agent
      image_name: tssc-maven-jenkins-agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check and verify version.json
        id: check_version
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          echo $(jq -r '.version' ${context}/version.json)
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          path: ${{ env.context }}
          push: false
          repository: ${{ env.image_name }}
          tags: ${{ steps.check_version.outputs.IMAGE_TAGS }}
      - name: Test image
        run: |
          echo "Running: docker run --entrypoint=which ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} run-jnlp-client"
          docker run --entrypoint=which ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} run-jnlp-client
          echo "Running: docker run --entrypoint=mvn ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} --version"  
          docker run --entrypoint=mvn ${image_name}:${{ steps.check_version.outputs.IMAGE_TAGS }} --version
